def aumentar(preco):
	conta= (preco*0.10)+preco
	return conta               
def diminuir(preco):
	conta= preco-(preco*0.10)
	return conta
def dobro(preco):
	conta= 2*preco
	return conta
def metade(preco):
	conta= preco//2
	return conta
